<a href="https://colab.research.google.com/github/BoKna031/AnimeRecommendationSystem/blob/google_colab/ARS_tidy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Possible ways to access the dataset:
1.   Access to the dataset via kaggle api (currently not an option due to a 403 error)
2.   Download manually dataset from kaggle and upload to the google drive

In [1]:
!pip install --user kaggle
! mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.8/dist-packages (1.5.12)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from kaggle) (2022.12.7)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.8/dist-packages (from kaggle) (8.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.25.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (4.0.0)
cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [2]:
! kaggle datasets download datasets/hernan4444/anime-recommendation-database-2020

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.8/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.8/dist-packages/kaggle/api/kaggle_api_extended.py", line 164, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.

Until I enable kaggle api, google drive will be used with defined paths to each csv files
Datasets:


1.   From https://www.kaggle.com/datasets/hernan4444/anime-recommendation-database-2020/discussion/352326 anime.csv, animelist.csv,
2.   From https://www.kaggle.com/datasets/CooperUnion/anime-recommendations-database rating.csv, anime.csv
3. https://www.kaggle.com/datasets/vishalmane10/anime-dataset-2022 Anime.csv

In [3]:
import os

DATASET_FOLDER = os.sep + 'content'+ os.sep +'drive'+ os.sep +'MyDrive'+ os.sep +'Colab Notebooks'+ os.sep +'dataset'
GENERATED_FOLDER = DATASET_FOLDER + os.sep + 'generated'

ANIME_CSV_PATH = DATASET_FOLDER + os.sep + 'anime.csv'
ANIME_ADDINFO_CSV_PATH = DATASET_FOLDER + os.sep + 'anime_with_synopsis.csv'
#BIG_RATINGS_CSV_PATH = DATASET_FOLDER + os.sep + 'animelist.csv'
SMALL_RATING_CSV_PATH = DATASET_FOLDER + os.sep + 'rating.csv'

defining paths to be used for generating and reading csv files

all the files that make up the basic dataset will be in the **dataset** folder, while the generated files will be in the **dataset/generated** folder

In [26]:
import pandas as pd
anime_df = pd.read_csv(ANIME_CSV_PATH)
anime_df.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [27]:
anime_df['Genres'] = anime_df['Genres'].str.split(', ')
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

In [28]:
anime_df.shape[0]
anime_df.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"[Action, Adventure, Comedy, Drama, Sci-Fi, Space]",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"[Action, Drama, Mystery, Sci-Fi, Space]",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"[Action, Sci-Fi, Adventure, Comedy, Drama, Sho...",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"[Action, Mystery, Police, Supernatural, Drama,...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"[Adventure, Fantasy, Shounen, Supernatural]",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [31]:
unique_genres = anime_df['Genres'].explode().unique()
unique_genres.sort()
print(unique_genres)

['Action' 'Adventure' 'Cars' 'Comedy' 'Dementia' 'Demons' 'Drama' 'Ecchi'
 'Fantasy' 'Game' 'Harem' 'Hentai' 'Historical' 'Horror' 'Josei' 'Kids'
 'Magic' 'Martial Arts' 'Mecha' 'Military' 'Music' 'Mystery' 'Parody'
 'Police' 'Psychological' 'Romance' 'Samurai' 'School' 'Sci-Fi' 'Seinen'
 'Shoujo' 'Shoujo Ai' 'Shounen' 'Shounen Ai' 'Slice of Life' 'Space'
 'Sports' 'Super Power' 'Supernatural' 'Thriller' 'Unknown' 'Vampire'
 'Yaoi' 'Yuri']

Inappropriate genres as *Hentai* should be removed.

In [34]:
inappropriate_content = ['Hentai']
mask = anime_df['Genres'].apply(lambda content: any(inap_cont in content for inap_cont in inappropriate_content))
inappropriate_df_index = anime_df[mask].index
mal_ids = anime_df.loc[inappropriate_df_index, 'MAL_ID']
anime_df = anime_df.drop(inappropriate_df_index)
print('removed rows: ', len(mal_ids))

In [36]:
unique_genres = anime_df['Genres'].explode().unique()
unique_genres.sort()
print(unique_genres)

['Action' 'Adventure' 'Cars' 'Comedy' 'Dementia' 'Demons' 'Drama' 'Ecchi'
 'Fantasy' 'Game' 'Harem' 'Historical' 'Horror' 'Josei' 'Kids' 'Magic'
 'Martial Arts' 'Mecha' 'Military' 'Music' 'Mystery' 'Parody' 'Police'
 'Psychological' 'Romance' 'Samurai' 'School' 'Sci-Fi' 'Seinen' 'Shoujo'
 'Shoujo Ai' 'Shounen' 'Shounen Ai' 'Slice of Life' 'Space' 'Sports'
 'Super Power' 'Supernatural' 'Thriller' 'Unknown' 'Vampire' 'Yaoi']

Now we can try to find data about *Unknown* animes from other available datasets

In [33]:
anime_with_unknown_genres = anime_df.loc[anime_df['Genres'].apply(lambda x: 'Unknown' in x)]
print(anime_with_unknown_genres.shape[0])

63

In [38]:
anime_with_unknown_genres.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
9788,28487,Ikite Iru,Unknown,[Unknown],Unknown,生きている,OVA,1,1996,Unknown,...,4.0,Unknown,2.0,1.0,2.0,8.0,Unknown,Unknown,Unknown,3.0
9838,28653,Maze,Unknown,[Unknown],Unknown,MAZE,Movie,1,2012,Unknown,...,7.0,Unknown,4.0,11.0,19.0,18.0,15.0,5.0,11.0,10.0
9839,28655,PiKA PiKA,5.12,[Unknown],Unknown,PiKA PiKA,Movie,1,2006,Unknown,...,4.0,2.0,5.0,27.0,45.0,55.0,47.0,18.0,23.0,35.0
10090,29655,Chanda Gou,Unknown,[Unknown],M.S. Chanda,チャンダ号,Movie,1,1964,Unknown,...,5.0,2.0,1.0,7.0,10.0,19.0,14.0,7.0,13.0,11.0
10145,29765,Metropolis (2009),5.93,[Unknown],Unknown,METROPOLIS,Movie,1,2009,Unknown,...,18.0,11.0,31.0,33.0,31.0,39.0,12.0,12.0,9.0,13.0

Warning: Total number of columns (35) exceeds max_columns (20) limiting to first (20) columns.

There is a small number of animes that contains *Unknown* as genre, we can manually enter that information. Because there is problem with showing list of all animes (interactive data table shows only first 5 records), I will create new csv file.

In [41]:
ANIME_WITH_UNKNOWN_GENRES_CSV_PATH = GENERATED_FOLDER + os.sep + 'unknown_genres_anime.csv'
anime_with_unknown_genres.to_csv(ANIME_WITH_UNKNOWN_GENRES_CSV_PATH, index = False)

**TODO**: find information about animes from unknown_genres_anime.csv